### PR TITLE
John more scripts

### PR DESCRIPTION
**Pull request by jwarnn**
I want to add a few more scripts so that we are not so reliant on my clarity dashboard which requires SSH access. These new scripts allow you to use your own Clarity credentials to get ids, and update plates/artifact names. I also added the backup to accession Clarity samples; it is simpler and should work more easily than the current one but will miss samples tested here at UPHL. That usually less than a dozen a week so it not the perfect; but will at least keep things moving in the lab.

Please make sure that these scripts work for you. You may need to install new libraries for them to work.

### CODE REVIEW

**Comment by jwarnn** [comment]
Tom; I have updated those two scripts that were not working. Could you try them again and see if they work now?

**Comment by tives82** [comment]
> Tom; I have updated those two scripts that were not working. Could you try them again and see if they work now?

These are both working. Will you update the 'clarity_ids.py' script as well to have the --user and --password flags required as well as make it verbose in case the wrong userID/password is entered?

**Comment by jwarnn** [comment]
Great idea. Those updates have been made.

**Review by tives82 — APPROVED** [review]
Scripts work as intended.

**Comment by jwarnn** [comment]
After approval I added to the usage comment that users need to have the role system administrator in Clarity for those scripts to work. I added this role to Tom and Erin.

**Pull request merged**
