### PR TITLE
Update accessioning for Clarity script

### PR DESCRIPTION
**Pull request by jwarnn**
Just wanted to get rid of the the old accessioning script as it had extra functionality that is no longer needed as the tracking of samples has changed on the laboratory side of things. I renamed the back-up, simpler script to the original's name and deleted the original.

### CODE REVIEW

**Comment by erinyoung** [comment]
Is this the script that I'll be using later today?

**Comment by jwarnn** [comment]
Yes.

**Comment by erinyoung** [comment]
Sweet! I'll review this PR then.

**Comment by erinyoung** [comment]
I think it works great!

Thank you for putting together the list of external drives that are needed.

For future reference, not all versions of python or pandas will work.

I created a conda environment with the following versions
```
% python --version
Python 3.7.16

```

```
% pip list
Package         Version
--------------- -----------
certifi         2022.12.7
et-xmlfile      1.1.0
numpy           1.21.6
openpyxl        3.1.2
pandas          1.3.5
pip             22.3.1
python-dateutil 2.9.0.post0
pytz            2024.1
setuptools      65.6.3
six             1.16.0
wheel           0.38.4

```

**Review by erinyoung — APPROVED** [review]

**Pull request merged**
