### PR TITLE
Update MiSeq_runs_basespace.sh with download complete file

### PR DESCRIPTION
**Pull request by jwarnn**
Adding the creation of trigger file for ICA automation with a few lines of code. It will create an empty text file in run directory which can be used to kick off another script.

### CODE REVIEW

**Comment by jwarnn** [comment]
Let's wait on this for a little bit; I am also going to included my upload bash script and update the README.md. That way we only need to do one pull request.

**Comment by jwarnn** [comment]
Ok now I am ready for review. You might also noticed I accidentally made my commits to the main branch at first. I reverted those two commits on the main branch and did them on my john-dev branch. Hopefully everything is copacetic.

**Review by erinyoung — CHANGES_REQUESTED** [review]
Off to a great start!

I think it'd be easier if upload_BS_to_ICA.sh were part of MiSeq_runs_basespace.sh

Also, we need to make sure that the linux workstation is configured correctly before we can put this into production.

**Comment by jwarnn** [comment]
Ok I added the important part of upload_BS_to_ICA.sh to MiSeq_runs_basespace.sh. I think icav2 should work.

**Review by erinyoung — APPROVED** [review]

**Comment by erinyoung** [comment]
I'm going to merge this and move it into master. It _shouldn't_ impact the main part of the production account. UT-M70330-220505 is running this weekend, so we'll have it be our test upload.

**Pull request merged**
