### PR TITLE
John update

### PR DESCRIPTION
**Pull request by jwarnn**
ICA made some updates on the file paths they use when uploading FASTQs from sequencer and this made auto_mycosnp no longer functional. This PR will fix that.

Also the analysis_for_run.py has started failing because the bs app was giving a 504 bad gateway error.  These errors are intermittent and resolved with restarting the scripts but I thought it best just to make it not break the script. 

Those are the two fixes that I have completed so far. I am testing the automations to make sure they work in the Prod account on the linux workstation as I have been using my own account. I still think we can and should house the scripts in my directory on the NAS, /Volumes/IDGenomics_NAS/Bioinformatics/jarnn/, as the log file and a configuration file is found there. I don't want to merge this PR till I have it working in Prod but didn't want to forget to do a PR so I thought it would be best to start one and get the ball rolling.

### CODE REVIEW

**Comment by jwarnn** [comment]
Looks like download_ica.py was broken. I think that I was trying to make it too specific as the icav2 app might not like the string lengths for the arguments. If I add anything to the path after the long folder name it could no longer find the data on ICA. It is working now and this PR is ready for review.

**Comment by jwarnn** [comment]
UT-M70330-240216 completed everything successfully and the code that gets around the bad gateway 502 error has also been working.

**Comment by jwarnn** [comment]
Can I get this reviewed and merged?

**Review by erinyoung — APPROVED** [review]

**Comment by erinyoung** [comment]
I think the changes that you made make sense.

**Pull request merged**
