### PR TITLE
Clarity accession

### PR DESCRIPTION
**Pull request by jwarnn**
This is a script that can be used to accession into Clairty if I am gone and my Dashboard is not working. Tom and Kelly have old versions of this script but the scripts would not work any more. I want this on the git repo in case I miss any days and I can track the changes that have been made. Any comments are appreciated especially on the README.md. If you want to try it out where you actually upload into Clarity please use Dev. Thanks.

### CODE REVIEW

**Review by erinyoung — COMMENTED** [review]
I don't think I'm the end user for this script, so I'm unsure how to test it. I'm also unsure if I should be approving this.

This looks okay to me, although I think pandas has some functionality to replace lines 172-225.

accession_for_clarity.py 
- looks for the NGS_Covid  LIMS exports
- looks for kfs workbooks and other files
- adjusts the column headers
- concatenates each dataframe (does not merge them)
- iterates over the dataframe to fix values

How come we aren't exporting the final file as an excel file? It seems like an unneeded extra step to open the file in excel and then save it as excel that way.

**Comment by jwarnn** [comment]
My idea was that anyone in the NGS group would be able to run this script if I was away from work for an extended period of time, because it is critical for the lab to be able to use Clarity. I was hoping everyone could get conformable running it.

I couldn't find a python library that would export the files in exactly the format Clarity is expecting with the header and also the xml like elements on certain rows/lines in the file.

**Comment by erinyoung** [comment]
> I couldn't find a python library that would export the files in exactly the format Clarity is expecting with the header and also the xml like elements on certain rows/lines in the file.

Sad day.

**Comment by jwarnn** [comment]
Original script was written for 3.8.8. It was not working in other versions of python. Made updates and test for several versions of python.

**Review by tives82 — APPROVED** [review]
Tested the modifications to the script and it ran successfully.

**Comment by erinyoung** [comment]
@tives82 Awesome! When you get a moment, can you merge this PR?

**Pull request merged**
